path: ./ # dataset root dir
train: train  # train images (relative to 'path')
val: valid  # val images (relative to 'path')
test: test  # test images (relative to 'path')

# Classes
names:
  0: "AUTOMOTIVE OIL"
  1: "BATTERY"
  # 0: "AIR COMPRESSOR"
  # 1: "ALTERNATOR"
  # 2: "BATTERY"
  # 3: "BRAKE CALIPER"
  # 4: "BRAKE PAD"
  # 5: "BRAKE ROTOR"
  # 6: "CAMSHAFT"
  # 7: "CARBERATOR"
  # 8: "CLUTCH PLATE"
  # 9: "COIL SPRING"
  # 10: "CRANKSHAFT"
  # 11: "CYLINDER HEAD"
  # 12: "DISTRIBUTOR"
  # 13: "ENGINE BLOCK"
  # 14: "ENGINE VALVE"
  # 15: "FUEL INJECTOR"
  # 16: "FUSE BOX"
  # 17: "GAS CAP"
  # 18: "HEADLIGHTS"
  # 19: "IDLER ARM"
  # 20: "IGNITION COIL"
  # 21: "INSTRUMENT CLUSTER"
  # 22: "LEAF SPRING"
  # 23: "LOWER CONTROL ARM"
  # 24: "MUFFLER"
  # 25: "OIL FILTER"
  # 26: "OIL PAN"
  # 27: "OIL PRESSURE SENSOR"
  # 28: "OVERFLOW TANK"
  # 29: "OXYGEN SENSOR"
  # 30: "PISTON"
  # 31: "PRESSURE PLATE"
  # 32: "RADIATOR"
  # 33: "RADIATOR FAN"
  # 34: "RADIATOR HOSE"
  # 35: "RADIO"
  # 36: "RIM"
  # 37: "SHIFT KNOB"
  # 38: "SIDE MIRROR"
  # 39: "SPARK PLUG"
  # 40: "SPOILER"
  # 41: "STARTER"
  # 42: "TAILLIGHTS"
  # 43: "THERMOSTAT"
  # 44: "TORQUE CONVERTER"
  # 45: "TRANSMISSION"
  # 46: "VACUUM BRAKE BOOSTER"
  # 47: "VALVE LIFTER"
  # 48: "WATER PUMP"
  # 49: "WINDOW REGULATOR"